### ISSUE TITLE
"Provide fallback img element for picture element" section makes no sense

### ISSUE THREAD

**Issue by thrnd** [hail2u/html-best-practices#71]
`<img>` inside a `<picture>` is not a fallback. If you omit `<img>` nothing will be displayed.

> The picture element is a container which provides multiples sources to its contained img element

https://www.w3.org/TR/html52/semantics-embedded-content.html#the-picture-element

**Comment by mrcaidev** [comment]
Indeed. A nested `<img>` is necessary for `<picture>` to show image.

But personally I think the author means that, the browser would always **prefer** to choose image among `<source>` tags, and the `<img>` would only function as a last resort when no source is suitable. (See [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)) That is to say, an `<img>` is a "necessary fallback".

So I think the problem is with the explanation: "The support of `picture` element is not good yet.". It makes this rule seems optional, which is in fact compulsory.

And again, this is only my personal opinion😊
